#!/bin/sh

#script for downloading latest anime episode via torrent using rss provided by website named "subsplease.org"

#parsing rss file
notify-send "Parsing SubsPlease RSS... Please Wait..." 
curl -s https://subsplease.org/rss/?r=720 | tr "><" ">\n<"  > $HOME/.cache/rss

#extracting names and providing the menu for selecting particular title
name=$(sed -n -e 's/title>\(\[SubsPlease\].*\)/\1/p' .cache/rss | sed -e 's/\[SubsPlease\] //g' -e 's/(.*//g' | dmenu -l 25 -p "Search anime:")

if [ -z "$name" ]; then
    notify-send -u critical "Err.. Query empty"
else
    #changing the name into format string for pattern matching
    query=$(printf "$name" | jq -rRs @uri)

    #finding the magnet link containing the exact pattern
    magnet=$(sed -n -e "s/link>\(.*$query.*\).*/\1/p" .cache/rss)

    #custom script for downloading torrent using aria2c.. you can use your own bittorrent client here
    st -e $HOME/repos_scripts/torrent "$magnet" &
fi
