#!/bin/sh

if [ -z "$*" ]; then
    magnet="$(cat .cache/maglink)"
else
    magnet=$*
fi

printf "Enter Directory (default:MOVIES) :"
read x

if [ -z "$x" ]; then
    x="MOVIES"
fi

notify-send "Torrent:Rukk ja Download ho rha hai"
echo "$magnet"
aria2c -d $x --seed-time=0 "$magnet" && notify-send "Torrent:cheecha download hogyi" || notify-send -u critical "Torrent:cheecha error!!"
